import { instagramMessages } from '../ai/prompts.js';
import { streamCloudflare } from '../ai/cloudflare.js';
import { streamOpenAI } from '../ai/openai.js';
import { getSettings, putRecord, readStoredSecret } from './kv.js';
import { sseResponse } from './research.js';
import { cleanText, httpError, readJson } from '../utils.js';

const num=v=>Number.isFinite(Number(v))?Number(v):0, clamp=v=>Math.round(Math.max(0,Math.min(100,v)));
const tags=text=>[...new Set((String(text||'').match(/#[\p{L}\p{N}_]+/gu)||[]).map(v=>v.toLowerCase()))];
function walk(value,out,seen=new WeakSet()){if(!value||typeof value!=='object'||seen.has(value))return;seen.add(value);const keys=Object.keys(value).map(v=>v.toLowerCase());if(keys.some(k=>['caption','media_type','timestamp','taken_at','permalink'].includes(k))&&keys.some(k=>['likes','like_count','comments','comments_count','reach','impressions','saves','saved','insights'].includes(k)))out.push(value);for(const child of Object.values(value)){if(Array.isArray(child))child.forEach(v=>walk(v,out,seen));else walk(child,out,seen);}}
function insight(post,names){const rows=post.insights?.data||post.insights||post.metrics||[];if(Array.isArray(rows)){for(const row of rows)if(names.includes(String(row.name||row.metric||'').toLowerCase()))return num(row.values?.[0]?.value??row.value);}for(const name of names)if(rows?.[name]!=null)return num(rows[name]);return 0;}
function normalize(post,i){const caption=cleanText(post.caption||post.title||post.text||''),reach=num(post.reach)||insight(post,['reach']),impressions=num(post.impressions)||insight(post,['impressions']),likes=num(post.like_count??post.likes),comments=num(post.comments_count??post.comments),saves=num(post.saved??post.saves)||insight(post,['saved','saves']),shares=num(post.shares)||insight(post,['shares']),views=num(post.plays??post.views??post.video_view_count)||insight(post,['plays','views']);const interactions=likes+comments+saves+shares,denominator=reach||impressions||views||0;let date=new Date(post.timestamp||post.taken_at||post.creation_timestamp||0);return{id:String(post.id||post.media_id||post.pk||`post-${i+1}`),caption,media_type:String(post.media_type||post.type||post.product_type||'UNKNOWN').toUpperCase(),timestamp:Number.isFinite(date.getTime())?date.toISOString():null,likes,comments,saves,shares,reach,impressions,views,interactions,engagement_rate:denominator?interactions/denominator:0,hashtags:tags(caption),caption_length:caption.length};}
function correlation(xs,ys){if(xs.length<3)return null;const ax=xs.reduce((a,b)=>a+b,0)/xs.length,ay=ys.reduce((a,b)=>a+b,0)/ys.length;let n=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const x=xs[i]-ax,y=ys[i]-ay;n+=x*y;dx+=x*x;dy+=y*y;}return dx&&dy?n/Math.sqrt(dx*dy):null;}
function analyze(posts,source){const dates=posts.map(p=>p.timestamp&&new Date(p.timestamp)).filter(Boolean).sort((a,b)=>a-b),days=dates.length>1?Math.max(1,(dates.at(-1)-dates[0])/86400000):30,formats={},hash={},heat=Array.from({length:7},()=>Array(24).fill(0)),counts=Array.from({length:7},()=>Array(24).fill(0));for(const p of posts){formats[p.media_type]=(formats[p.media_type]||0)+1;if(p.timestamp){const d=new Date(p.timestamp);heat[d.getUTCDay()][d.getUTCHours()]+=p.engagement_rate||p.interactions;counts[d.getUTCDay()][d.getUTCHours()]++;}for(const tag of p.hashtags){hash[tag]||={uses:0,total:0};hash[tag].uses++;hash[tag].total+=p.engagement_rate;}}const rates=posts.map(p=>p.engagement_rate).filter(Boolean),avg=rates.length?rates.reduce((a,b)=>a+b,0)/rates.length:0,weekly=posts.length/days*7,breakdown={consistency:clamp(weekly/4*100),engagement_rate:clamp(avg/.06*100),content_variety:clamp(Object.keys(formats).length/4*100),caption_quality:clamp(posts.some(p=>p.caption_length>=80)?75:48),hashtag_strategy:clamp(Object.keys(hash).length?65:25)},ranked=[...posts].sort((a,b)=>(b.engagement_rate||b.interactions)-(a.engagement_rate||a.interactions));return{source,sample_size:posts.length,period:{first_post:dates[0]?.toISOString()||null,last_post:dates.at(-1)?.toISOString()||null,days:Math.round(days)},averages:{engagement_rate:avg,caption_length:posts.reduce((a,p)=>a+p.caption_length,0)/posts.length,hashtags_per_post:posts.reduce((a,p)=>a+p.hashtags.length,0)/posts.length,posts_per_week:weekly},health_score:clamp(Object.values(breakdown).reduce((a,b)=>a+b,0)/5),score_breakdown:breakdown,formats,best_posts:ranked.slice(0,5),worst_posts:ranked.slice(-5).reverse(),heatmap:heat.map((row,d)=>row.map((v,h)=>counts[d][h]?v/counts[d][h]:0)),hashtags:Object.entries(hash).map(([tag,v])=>({tag,uses:v.uses,average_engagement:v.total/v.uses})).sort((a,b)=>b.average_engagement-a.average_engagement).slice(0,30),caption_engagement_correlation:correlation(posts.map(p=>p.caption_length),posts.map(p=>p.engagement_rate||p.interactions)),posts:posts.slice(0,200),limitations:[posts.length<10?'Small sample: fewer than 10 posts were available.':null,!posts.some(p=>p.reach)?'Reach was missing for some or all posts.':null].filter(Boolean)};}
export function parseInstagramData(payload,source='manual'){const raw=[];walk(payload,raw);const unique=new Map();raw.map(normalize).forEach(p=>unique.set(p.id,p));const posts=[...unique.values()].filter(p=>p.caption||p.timestamp||p.interactions||p.reach||p.impressions||p.views);if(!posts.length)throw httpError(400,'No post-level Instagram records were found.');return analyze(posts,source);}
async function run(env,metrics,preference){const settings=await getSettings(env),selected=(preference||settings.model)==='gpt55'?await streamOpenAI(env,{messages:instagramMessages({...metrics,posts:metrics.posts.slice(0,60)}),maxTokens:7000}):await streamCloudflare(env,{messages:instagramMessages({...metrics,posts:metrics.posts.slice(0,60)}),maxTokens:7000});const id=`${Date.now()}-instagram-analysis`;return sseResponse({meta:{id,metrics,model:selected.model,provider:selected.provider},source:selected.stream,onDone:report=>putRecord(env,'instagram',{id,type:'instagram',title:`Instagram analysis · ${new Date().toISOString().slice(0,10)}`,report,content:report,metrics,model:selected.model,provider:selected.provider})});}
export async function handleInstagramAnalysis(request,env){const body=await readJson(request);let payload=body.data;if(typeof payload==='string'){try{payload=JSON.parse(payload);}catch{throw httpError(400,'The pasted Instagram data is not valid JSON.');}}if(!payload||typeof payload!=='object')throw httpError(400,'Paste Instagram JSON before analyzing.');return run(env,parseInstagramData(payload),body.model);}
async function graph(url,token){const response=await fetch(url,{headers:{Authorization:`Bearer ${token}`}}),data=await response.json().catch(()=>({}));if(!response.ok||data.error)throw httpError(response.status||502,data.error?.message||'Instagram Graph API request failed.');return data;}
export async function handleInstagramSync(request,env){const body=await readJson(request,{}),token=env.INSTAGRAM_ACCESS_TOKEN||await readStoredSecret(env,'instagram',String(body.pin||''));if(!token)throw httpError(503,'No Instagram token is configured.');const root=`${env.INSTAGRAM_GRAPH_BASE_URL||'https://graph.instagram.com'}/${env.INSTAGRAM_GRAPH_VERSION||'v25.0'}`,profile=await graph(`${root}/me?fields=id,username,followers_count,media_count`,token),media=await graph(`${root}/${encodeURIComponent(profile.id)}/media?fields=id,caption,media_type,media_product_type,timestamp,like_count,comments_count,permalink&limit=100`,token);const enriched=await Promise.all((media.data||[]).map(async post=>{try{return{...post,insights:await graph(`${root}/${encodeURIComponent(post.id)}/insights?metric=reach,impressions,saved,shares,plays,total_interactions`,token)};}catch{return post;}}));const metrics=parseInstagramData({profile,media:enriched},'instagram_graph_api');metrics.profile=profile;return run(env,metrics,body.model);}
