import { renderDashboard } from './views/dashboard.js';
import { renderResearch } from './views/research.js';
import { renderInstagram, SAMPLE_IG_DATA } from './views/instagram.js';
import { renderSaved } from './views/saved.js';
import { renderSettings } from './views/settings.js';

const state={authenticated:false,bootstrap:null,settings:{model:'cloudflare',default_research_mode:'deep',response_length:'balanced',theme:'dark'},researchMode:'',researchSession:null,researchText:'',instagramSession:null,instagramText:'',instagramMetrics:null,savedItems:[],savedFilter:'all',savedQuery:''};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,type='ok'){const n=document.createElement('div');n.className=`toast ${type}`;n.textContent=message;$('#toasts').append(n);setTimeout(()=>n.remove(),3400);}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(response.status===401){showLogin();throw new Error('Your session expired. Sign in again.');}const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false)throw new Error(data.error||`Request failed (${response.status}).`);return data;}
function route(){const r=location.hash.replace(/^#\//,'').split('/')[0];return['dashboard','research','instagram','saved','settings'].includes(r)?r:'dashboard';}
function title(r){return({dashboard:'Dashboard',research:'Research Engine',instagram:'Instagram Insights',saved:'Saved Library',settings:'Settings'})[r];}
function apply(){document.documentElement.dataset.theme=state.settings.theme||'dark';const g=state.settings.model==='gpt55';$('#modelPill').textContent=g?'GPT-5.5 Thinking':'Cloudflare AI';$('#modelTitle').textContent=g?'GPT-5.5 Thinking':'Cloudflare AI';$('#modelSubtitle').textContent=g?'High reasoning effort':'Llama 4 Scout';$('#modelToggle').classList.toggle('on',g);}
function sidebar(){const recent=state.bootstrap?.recent||[];$('#recent').innerHTML=recent.slice(0,6).map(i=>`<a href="#/${i.type==='instagram'?'instagram':'research'}" data-recent="${esc(i.id)}">${i.type==='instagram'?'◎':'◇'} <span>${esc(i.title||i.query||'Untitled')}</span></a>`).join('')||'<p>No sessions yet</p>';apply();}
function showLogin(){state.authenticated=false;$('#app').hidden=true;$('#loginView').hidden=false;setTimeout(()=>$('#password')?.focus(),0);}
async function refresh(){const data=await api('/api/bootstrap');state.bootstrap=data;state.settings=data.settings;state.researchMode||=data.settings.default_research_mode;sidebar();}
async function showApp(){state.authenticated=true;$('#loginView').hidden=true;$('#app').hidden=false;await refresh();if(!location.hash)location.hash='#/dashboard';render();}
function markdown(text){let s=esc(String(text||''));return s.split('\n').map(line=>{const h=line.match(/^(#{1,4})\s+(.+)$/);if(h)return`<h${Math.min(4,h[1].length+1)}>${h[2]}</h${Math.min(4,h[1].length+1)}>`;if(/^[-*]\s+/.test(line))return`<li>${line.replace(/^[-*]\s+/,'')}</li>`;return line.trim()?`<p>${line}</p>`:'';}).join('').replace(/(<li>.*?<\/li>)+/g,m=>`<ul>${m}</ul>`).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');}
async function stream(path,body,handlers){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Accept:'text/event-stream'},body:JSON.stringify(body)});if(response.status===401){showLogin();throw new Error('Your session expired.');}if(!response.ok||!response.body){const d=await response.json().catch(()=>({}));throw new Error(d.error||'Request failed.');}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const{value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split(/\n\n/);buffer=events.pop()||'';for(const raw of events){const event=raw.match(/^event:\s*(.+)$/m)?.[1]?.trim()||'message',line=raw.match(/^data:\s*(.+)$/m)?.[1];if(!line)continue;const data=JSON.parse(line);if(event==='error')throw new Error(data.error);await handlers[event]?.(data);}}}
function download(name,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`# ${name}\n\n${content}`],{type:'text/markdown'}));a.download=`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'creatoriq'}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function openItem(item){if(!item)return;const d=document.createElement('dialog');d.className='content-dialog';d.innerHTML=`<div class="dialog-head"><h2>${esc(item.title||'Saved insight')}</h2><button class="icon">×</button></div><article class="markdown">${markdown(item.content||item.report||'')}</article>`;d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();document.body.append(d);d.showModal();}
function bindDashboard(){$$('[data-open]').forEach(c=>c.onclick=()=>{const item=[...(state.bootstrap?.recent||[]),...(state.bootstrap?.pinned||[])].find(i=>i.id===c.dataset.open);if(!item)return;if(c.dataset.type==='instagram'){state.instagramSession=item;state.instagramText=item.report||item.content||'';state.instagramMetrics=item.metrics;location.hash='#/instagram';}else{state.researchSession=item;state.researchText=item.content||'';location.hash='#/research';}});}
function hydrateResearch(){if(!state.researchSession)return;$('#researchResult').hidden=false;$('#researchTitle').textContent=state.researchSession.title||state.researchSession.query;$('#researchStatus').textContent='Complete';$('#researchOutput').innerHTML=markdown(state.researchText);}
function bindResearch(){hydrateResearch();$$('[data-mode]').forEach(b=>b.onclick=()=>{state.researchMode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));});$$('[data-suggestion]').forEach(b=>b.onclick=()=>{$('#researchQuery').value=b.dataset.suggestion;});$('#researchForm').onsubmit=async e=>{e.preventDefault();const query=$('#researchQuery').value.trim();if(!query)return;$('#researchResult').hidden=false;$('#researchTitle').textContent=query;$('#researchStatus').textContent='Thinking and streaming';$('#researchOutput').innerHTML='';state.researchText='';try{await stream('/api/research',{query,mode:state.researchMode,model:state.settings.model,response_length:state.settings.response_length},{meta:d=>state.researchSession={...d,title:query,type:'research'},delta:d=>{$('#researchOutput').innerHTML=markdown(state.researchText+=d.delta||'');},done:async d=>{state.researchSession.id=d.id;$('#researchStatus').textContent='Complete';await refresh();}});}catch(err){$('#researchStatus').textContent='Failed';toast(err.message,'error');}};$('#copyResearch').onclick=()=>navigator.clipboard.writeText(state.researchText).then(()=>toast('Copied.'));$('#exportResearch').onclick=()=>download(state.researchSession?.title||'CreatorIQ research',state.researchText);$('#saveResearch').onclick=async()=>{if(!state.researchSession?.id)return toast('Run research first.','error');await api('/api/saved',{method:'POST',body:JSON.stringify({source_collection:'research',source_id:state.researchSession.id,type:state.researchSession.mode||'research'})});toast('Saved.');};$('#pinResearch').onclick=async()=>{if(!state.researchSession?.id)return;const d=await api(`/api/research/${encodeURIComponent(state.researchSession.id)}/pin`,{method:'POST',body:'{}'});state.researchSession=d.item;await refresh();toast(d.item.pinned?'Pinned.':'Unpinned.');};$('#followupForm').onsubmit=async e=>{e.preventDefault();const q=$('#followupInput').value.trim(),o=$('#followupOutput');if(!q||!state.researchSession?.id)return;o.hidden=false;o.innerHTML='';let t='';try{await stream('/api/chat',{question:q,session_id:state.researchSession.id,session_type:'research',model:state.settings.model},{delta:d=>o.innerHTML=markdown(t+=d.delta||'')});}catch(err){toast(err.message,'error');}};}
function drawMetrics(m){if(!m)return;$('#scoreOverview').innerHTML=`<article><div class="ring" style="--score:${m.health_score}">${m.health_score}</div><div><p class="eyebrow">Content health score</p><h3>${m.sample_size} posts analyzed</h3></div></article><div>${Object.entries(m.score_breakdown||{}).map(([k,v])=>`<label>${k.replace(/_/g,' ')}<span><i style="width:${v}%"></i></span><b>${v}</b></label>`).join('')}</div>`;const max=Math.max(.0001,...(m.heatmap||[]).flat());$('#heatmap').innerHTML=`<div class="heat">${(m.heatmap||[]).flatMap((row,d)=>[`<b>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]}</b>`,...row.map(v=>`<i style="--a:${Math.max(.05,v/max)}"></i>`)]).join('')}</div>`;const c=$('#formatChart'),ctx=c.getContext('2d'),entries=Object.entries(m.formats||{}),mx=Math.max(1,...entries.map(x=>x[1]));ctx.clearRect(0,0,c.width,c.height);ctx.font='14px Inter';entries.forEach(([k,v],i)=>{const y=35+i*46;ctx.fillStyle='#6B6B8A';ctx.fillText(k,10,y);ctx.fillStyle='#7C6FFF';ctx.fillRect(155,y-14,v/mx*280,20);ctx.fillText(String(v),450,y);});}
function hydrateIg(){if(!state.instagramSession)return;$('#igReport').hidden=false;$('#igStatus').textContent='Complete';$('#igOutput').innerHTML=markdown(state.instagramText);drawMetrics(state.instagramMetrics);}
function bindInstagram(){hydrateIg();$('#loadSample').onclick=()=>$('#igJson').value=JSON.stringify(SAMPLE_IG_DATA,null,2);const run=async(path,body)=>{state.instagramText='';$('#igReport').hidden=false;$('#igOutput').innerHTML='';$('#igStatus').textContent='Analyzing and streaming';try{await stream(path,body,{meta:d=>{state.instagramSession={...d,title:'Instagram report',type:'instagram'};state.instagramMetrics=d.metrics;drawMetrics(d.metrics);},delta:d=>$('#igOutput').innerHTML=markdown(state.instagramText+=d.delta||''),done:async d=>{state.instagramSession.id=d.id;$('#igStatus').textContent='Complete';await refresh();}});}catch(err){$('#igStatus').textContent='Failed';toast(err.message,'error');}};$('#analyzeIg').onclick=()=>{const data=$('#igJson').value.trim();if(!data)return toast('Paste JSON first.','error');run('/api/instagram/analyze',{data,model:state.settings.model});};$('#syncIg').onclick=()=>run('/api/instagram/sync',{pin:$('#igPin').value,model:state.settings.model});$('#saveIg').onclick=async()=>{if(!state.instagramSession?.id)return;await api('/api/saved',{method:'POST',body:JSON.stringify({source_collection:'instagram',source_id:state.instagramSession.id,type:'instagram'})});toast('Saved.');};$('#pinIg').onclick=async()=>{const d=await api(`/api/instagram/${encodeURIComponent(state.instagramSession.id)}/pin`,{method:'POST',body:'{}'});state.instagramSession=d.item;await refresh();toast(d.item.pinned?'Pinned.':'Unpinned.');};$('#exportIg').onclick=()=>download('CreatorIQ Instagram report',state.instagramText);$('#dataChatForm').onsubmit=async e=>{e.preventDefault();const q=$('#dataChatInput').value.trim(),o=$('#dataChatOutput');if(!q)return;o.hidden=false;let t='';await stream('/api/chat',{question:q,session_id:state.instagramSession.id,session_type:'instagram',model:state.settings.model},{delta:d=>o.innerHTML=markdown(t+=d.delta||'')}).catch(err=>toast(err.message,'error'));};}
async function loadSaved(){const type=state.savedFilter==='all'?'':state.savedFilter;state.savedItems=(await api(`/api/saved?type=${encodeURIComponent(type)}&q=${encodeURIComponent(state.savedQuery)}`)).items;}
function bindSaved(){let timer;$('#savedSearch').oninput=e=>{clearTimeout(timer);state.savedQuery=e.target.value;timer=setTimeout(async()=>{await loadSaved();render();},250);};$$('[data-filter]').forEach(b=>b.onclick=async()=>{state.savedFilter=b.dataset.filter;await loadSaved();render();});$$('[data-open-saved]').forEach(b=>b.onclick=()=>openItem(state.savedItems.find(i=>i.id===b.dataset.openSaved)));$$('[data-pin-saved]').forEach(b=>b.onclick=async()=>{await api(`/api/saved/${encodeURIComponent(b.dataset.pinSaved)}/pin`,{method:'POST',body:'{}'});await Promise.all([loadSaved(),refresh()]);render();});$$('[data-delete-saved]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this saved item?'))return;await api(`/api/saved/${encodeURIComponent(b.dataset.deleteSaved)}`,{method:'DELETE'});await loadSaved();render();});}
function bindSettings(){const f=$('#settingsForm');f.default_research_mode.value=state.settings.default_research_mode;f.response_length.value=state.settings.response_length;f.onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(f));body.clear_openai_key=f.clear_openai_key.checked;body.clear_instagram_token=f.clear_instagram_token.checked;$('#settingsStatus').textContent='Saving…';try{state.settings=(await api('/api/settings',{method:'PUT',body:JSON.stringify(body)})).settings;await refresh();apply();$('#settingsStatus').textContent='Saved';toast('Settings updated.');}catch(err){toast(err.message,'error');}};$('#clearData').onclick=async()=>{if(prompt('Type DELETE to clear all CreatorIQ data.')!=='DELETE')return;await api('/api/data/clear',{method:'DELETE',body:JSON.stringify({confirmation:'DELETE'})});state.researchSession=null;state.instagramSession=null;await refresh();location.hash='#/dashboard';};}
async function render(){if(!state.authenticated)return;const r=route();$('#pageTitle').textContent=title(r);$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r));if(r==='saved')await loadSaved();$('#main').innerHTML=({dashboard:renderDashboard,research:renderResearch,instagram:renderInstagram,saved:renderSaved,settings:renderSettings})[r](state);({dashboard:bindDashboard,research:bindResearch,instagram:bindInstagram,saved:bindSaved,settings:bindSettings})[r]();$('#main').focus({preventScroll:true});}
function bindShell(){window.onhashchange=render;$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';await showApp();}catch(err){$('#loginError').textContent=err.message;}};$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});showLogin();};$('#modelToggle').onclick=async()=>{state.settings=(await api('/api/settings',{method:'PUT',body:JSON.stringify({model:state.settings.model==='gpt55'?'cloudflare':'gpt55'})})).settings;apply();render();};$('#searchButton').onclick=()=>{$('#searchDialog').showModal();$('#searchInput').focus();};$('#searchInput').oninput=async e=>{const q=e.target.value.trim();if(q.length<2)return $('#searchResults').innerHTML='<p>Type at least two characters.</p>';const items=(await api(`/api/saved?q=${encodeURIComponent(q)}`)).items;$('#searchResults').innerHTML=items.map(i=>`<button data-search="${esc(i.id)}"><span class="badge">${esc(i.type)}</span><strong>${esc(i.title)}</strong></button>`).join('')||'<p>No matches.</p>';$$('[data-search]').forEach(b=>b.onclick=()=>{openItem(items.find(i=>i.id===b.dataset.search));$('#searchDialog').close();});};document.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchDialog').showModal();}};}
async function init(){bindShell();try{const s=await api('/api/auth/status');s.authenticated?await showApp():showLogin();}catch(err){showLogin();$('#loginError').textContent=err.message;}}init();
